README.md

Closes #13 
Added info about debian repo into readme

#13 - expand readme

---

pom.xml
src/main/java/com/artipie/debian/metadata/Control.java
src/main/java/com/artipie/debian/metadata/package-info.java
src/test/java/com/artipie/debian/metadata/ControlFromBinaryTest.java
src/test/java/com/artipie/debian/metadata/package-info.java

Part of #11 
Implemented reading control metadata file from debian binary.

#11 - read control file

---

pom.xml
src/main/java/com/artipie/debian/metadata/Control.java
src/test/java/com/artipie/debian/metadata/ControlFromBinaryTest.java

Part of #11 
Support xz compression

#11 - support xz compression

---

src/main/java/com/artipie/debian/metadata/ControlField.java
src/test/java/com/artipie/debian/metadata/ControlFieldTest.java

Part of #11 
Added class to extract architecture from control file

#11 - control file fields

---

src/main/java/com/artipie/debian/metadata/PackagesItem.java
src/test/java/com/artipie/debian/metadata/PackagesItemTest.java

Part of #11 
Added `PackagesItem` class to extend control metadata.

#11 - PackagesItem added

---

src/main/java/com/artipie/debian/metadata/Package.java
src/test/java/com/artipie/debian/metadata/PackageSimpleTest.java

Part of #11 
Added functionality to append package info to Packages index.

#11 - append info to the packages index

---

src/main/java/com/artipie/debian/http/DebianSlice.java
src/test/java/com/artipie/debian/DebianSliceITCase.java
src/test/java/com/artipie/debian/http/UpdateSliceTest.java

Closes #11 
Implemented update, added `UpdateSlice` to `DebianSlice`.

#11 - Update implemented

---

src/main/java/com/artipie/debian/metadata/PackagesItem.java
src/test/java/com/artipie/debian/metadata/PackagesItemTest.java

Closes #19 
Added sha1 and sha256 digests to Packages item

#19 - added sha1 and sha256 digests

---

src/test/java/com/artipie/debian/DebianAuthSliceITCase.java

Closes #12 
Added IT with auth.

#12 - IT with auth

---

README.md

Part of #28 
Update readme.md with info about Release file

#28 - added info about Release files to readme

---

pom.xml
src/main/java/com/artipie/debian/Config.java
src/main/java/com/artipie/debian/package-info.java
src/test/java/com/artipie/debian/ConfigFromYamlTest.java

Part of #28 
Added class for repository config.

#28 - added configuration

---

README.md
src/main/java/com/artipie/debian/metadata/Release.java
src/test/java/com/artipie/debian/metadata/ReleaseAstoTest.java
src/test/resources/Release

Part of #28 
Added `Release` interface and part of the implementation to create the file

#28 - create Release file

---

src/main/java/com/artipie/debian/metadata/Release.java
src/test/java/com/artipie/debian/metadata/ReleaseAstoTest.java

Part of #28 
Implemented Release index file update

#28 - implemented Release file update

---

src/test/java/com/artipie/debian/DebianSliceITCase.java
src/test/java/com/artipie/debian/http/ReleaseSliceTest.java

Part of #28 
Added unit test for `ReleaseSlice`

#28 - unit test for ReleaseSlice

---

src/main/java/com/artipie/debian/metadata/Package.java

Part of #41 
Used `ContentAsArchive` in `Package.Asto`

#41 - use ContentAsArchive

---

src/main/java/com/artipie/debian/misc/UnpackedContent.java
src/test/java/com/artipie/debian/misc/UnpackedContentTest.java

Part of #41 
Unpack and calculate digest and size at the same time

#41 - calc digest and size while unpacking

---

src/main/java/com/artipie/debian/metadata/Release.java
src/test/java/com/artipie/debian/metadata/ReleaseAstoTest.java

Part of #41 
Update Release index with info of the Package index

#41 - update Release index

---

src/main/java/com/artipie/debian/metadata/Release.java
src/test/java/com/artipie/debian/metadata/ReleaseAstoTest.java

Part of #41 
Fixed `SHA256` field format on Release index file creation

#41 - create release index part

---

pom.xml
src/main/java/com/artipie/debian/misc/GpgClearsign.java

Closes #29 
Partly refactored `GpgClearsign` class, left todo to continue

#29 - partly refactored GpgClearsign class

---

src/main/java/com/artipie/debian/Config.java
src/main/java/com/artipie/debian/GpgConfig.java
src/test/java/com/artipie/debian/ConfigFromYamlTest.java
src/test/java/com/artipie/debian/DebianAuthSliceITCase.java
src/test/java/com/artipie/debian/DebianGpgSliceITCase.java
src/test/java/com/artipie/debian/DebianSliceITCase.java
src/test/java/com/artipie/debian/GpgConfigTest.java
src/test/java/com/artipie/debian/http/UpdateSliceTest.java
src/test/java/com/artipie/debian/metadata/ReleaseAstoTest.java

Part of #51 
Added settings for gpg

#51 - Created interface and impl for gpg-settings

---

src/main/java/com/artipie/debian/Debian.java
src/test/java/com/artipie/debian/DebianTest.java

Part of #51
Implemented `Debian.Asto.updatePackages()`

#51 - implemented Debian.Asto.updatePackages

---

README.md

Updated description about `Release` files `SHA256` field

#0 - actualize README.md

---

src/main/java/com/artipie/debian/metadata/InRelease.java
src/test/java/com/artipie/debian/metadata/InReleaseAstoTest.java

Part of #51 
Added `InRelease` interface, implementation and test.

#51 - created InRelease interface and implementation

---

src/main/java/com/artipie/debian/metadata/Release.java
src/test/java/com/artipie/debian/DebianGpgSliceITCase.java
src/test/java/com/artipie/debian/http/ReleaseSliceTest.java
src/test/java/com/artipie/debian/metadata/ReleaseAstoTest.java

Part of #51 
`Release.Asto` now generates `Release.gpg` file if necessary

#51 - made Release.Asto generate gpg sign

---

src/main/java/com/artipie/debian/Debian.java
src/test/java/com/artipie/debian/DebianTest.java
src/test/java/com/artipie/debian/metadata/InReleaseAstoTest.java

Part of #51 
Fully implemented `Debian.Asto` and added tests.

#51 - Debian.Asto fully implemented

---

src/main/java/com/artipie/debian/http/ReleaseSlice.java
src/test/java/com/artipie/debian/DebianGpgSliceITCase.java
src/test/java/com/artipie/debian/http/ReleaseSliceTest.java

Part of #51 
Added `InRelease` index generation to `ReleaseSlice` and corrected tests.

#51 - generate InRelease in ReleaseSlice

---

src/main/java/com/artipie/debian/MultiDebian.java
src/test/java/com/artipie/debian/MultiDebianTest.java

Part of #87 
Added class to merge `Packages` checking for duplicates and simple test. More tests will be added in the next PR.

Merge Packages indexes

---

src/main/java/com/artipie/debian/MultiDebian.java
src/main/java/com/artipie/debian/metadata/UniquePackage.java
src/test/java/com/artipie/debian/metadata/UniquePackageTest.java

Closes #92 
Fixed bug with adding packages with the same name and different version.

New same packages with diff version

---

src/main/java/com/artipie/debian/MultiPackages.java
src/test/java/com/artipie/debian/MultiDebianTest.java
src/test/java/com/artipie/debian/MultiPackagesTest.java

Part of #87 
Added more tests for `MultiDebian.MergedPackages` class

Added test for Packages indexes merge

---

pom.xml
src/main/java/com/artipie/debian/benchmarks/IndexMergeBench.java
src/main/java/com/artipie/debian/benchmarks/package-info.java

Path of #98 
Added benchmark for index merge.

Benchmarks for index merge

---

README.md

Part of #98 
Added description for benchmarks and `IndexMergeBench`

Extended readme with benchmarks description

---

src/main/java/com/artipie/debian/benchmarks/RepoUpdateBench.java

Part of #98 
Added another benchmark for repository update.

Created benchmark for repository update

---

README.md

Closes #98 
Added information about `RepoUpdateBench` into readme

Added info about `RepoUpdateBench` into readme

---

pom.xml
src/main/java/com/artipie/debian/MultiPackages.java
src/main/java/com/artipie/debian/misc/GpgClearsign.java

Closes #104 
Updated `asto` and used `ArtipieException` for classes used by cloud artifact.

Updated `asto` and used `ArtipieException`

---

.github/workflows/maven-bench.yml
benchmarks/src/main/java/com/artipie/debian/benchmarks/RepoUpdateBench.java

Closes #106 
Used `BenchmarkStorage` in `RepoUpdateBench` and added `main` method, added action to build benchmarks

Used `BenchmarkStorage`, added CI script

---

.github/workflows/release.yml
CHANGELOG.md

Added release script and CHANGELOG.md

Added release script and CHANGELOG.md

---

.github/workflows/benchmarks.yml

Part of artipie/artipie#431
Remove some lines for copying results because it is included into `make` step. Use custom actions for running benchmarks and creating PR

ci: enhance code benchmarks workflow
