artipie/debian-adapter

src/main/java/com/artipie/debian/metadata/Package.java
src/test/java/com/artipie/debian/metadata/PackageSimpleTest.java

Part of #11 
Append package info when `Packages.gz`does not exist.

#11 - append info to the new packages index

---

src/test/java/com/artipie/debian/DebianSliceITCase.java
src/test/resources/Release

Part of #28 
Added IT for install with release file. How is this file used? Apt-get reads Architectures and Components fields and requests packages only from corresponding repository directories (in our case - only from amd64 as it's container architecture and our repo supports it according to this Release file).

#28 - test with release file

---

src/main/java/com/artipie/debian/Config.java
src/main/java/com/artipie/debian/http/DebianSlice.java
src/main/java/com/artipie/debian/http/ReleaseSlice.java
src/main/java/com/artipie/debian/http/UpdateSlice.java
src/main/java/com/artipie/debian/metadata/Package.java
src/test/java/com/artipie/debian/DebianAuthSliceITCase.java
src/test/java/com/artipie/debian/DebianSliceITCase.java
src/test/java/com/artipie/debian/http/UpdateSliceTest.java
src/test/java/com/artipie/debian/metadata/PackageAstoTest.java

Part of #28 
Created `ReleaseSlice` slice decorator (test will be added later) to create absent Release index file of requests and made `Package` to update Release after Packages index was updated.

#28 - added Release index create/update for the repo

---

src/main/java/com/artipie/debian/http/ReleaseSlice.java
src/main/java/com/artipie/debian/metadata/Release.java
src/test/java/com/artipie/debian/metadata/PackageAstoTest.java
src/test/java/com/artipie/debian/metadata/ReleaseAstoTest.java

Part of #28 
Added `key()` method to `Release` interface to avoid code repetition to obtaining this key.

#28 - Release key

---

src/main/java/com/artipie/debian/metadata/Package.java

Closes #49 
Do not pass decompressed Packages index files bytes.

#49 - do not pass decompressed bytes

---

src/test/java/com/artipie/debian/DebianSliceITCase.java

Closes #41 
I've corrected IT case matchers: apt-get should read Release index `SHA256` field and request Packages indexes listed there, and do not perform other extra requests.

#41 - corrected IT case

---

src/main/java/com/artipie/debian/Debian.java

Part of #51 
This is the interface I'd suggest exposing as sdk for our Chinese colleagues and preliminary implementation from the storage and repo config. We'll also need to add settings required by gpg-signing to the `Config`.
Creating/updating release index file process is already implemented in `Release` interface implementation and will be reused here.

#51 - Debian interface created

---

src/main/java/com/artipie/debian/Debian.java

Part of #51 
I've extended `Debian` with the methods to update info about provided `Packages` index file. This operation is faster than update info about all the `Packages` index files of the repo and as we know what `Packages` index file was changed it would be better to update info about this file only.

#51 - extend debian interface

---

src/main/java/com/artipie/debian/misc/GpgClearsign.java
src/test/java/com/artipie/debian/DebianGpgSliceITCase.java
src/test/java/com/artipie/debian/misc/GpgClearsignTest.java

Part of #29
Added test for the case with `Release` and `Release.gpg` files, corrected `GpgClearsign` to generate correct signature.

#29 - IT for gpg

---

src/main/java/com/artipie/debian/metadata/Package.java
src/test/java/com/artipie/debian/metadata/PackageAstoTest.java

Part of #51 
`Packages.gz` index files can be huge, that's way we should not fully load them into memory. To avoid that I've made `Package.Asto` implementation work with temp files instead of byte arrays.

#51 - work with files

---

src/main/java/com/artipie/debian/misc/UnpackedContent.java
src/test/java/com/artipie/debian/misc/UnpackedContentTest.java

Part of #51 
Made `UnpackedContent` to write publisher into temp file and then unpack it to avoid memory consumption.

#51 - UnpackedContent: do not read whole file into memory

---

src/test/java/com/artipie/debian/DebianTest.java
src/test/java/com/artipie/debian/GzArchive.java
src/test/java/com/artipie/debian/http/UpdateSliceTest.java
src/test/java/com/artipie/debian/metadata/PackageAstoTest.java
src/test/java/com/artipie/debian/metadata/ReleaseAstoTest.java

Closes #66 
Created `GzArchive` in test scope to pack/unpack `.gz` and used it in tests, removed all duplications.

#66 - created GzArchive

---

src/main/java/com/artipie/debian/http/UpdateSlice.java
src/test/java/com/artipie/debian/http/UpdateSliceTest.java

Closes #78 
Made `UpdateSlice` generate `InRelease` index after `deb` packaged was uploaded and `Release` index generated. Corrected corresponding test.

Generate InRelease index on upload

---

src/main/java/com/artipie/debian/http/UpdateSlice.java
src/main/java/com/artipie/debian/metadata/Release.java
src/test/java/com/artipie/debian/DebianGpgSliceITCase.java
src/test/java/com/artipie/debian/metadata/ReleaseAstoTest.java

Closes #80 
Fixed problem with missing line break at the end of the `Release` file, corrected `ReleaseAstoTest` to verify file ends with `\n`,
extended `DebianGpgSliceITCase` with upload and fixed logical mistake in `UpdateSlice` - `InRelease` index should be generated after `Release` was updated with each `Packages.gz` info.

Fix problem with missing line break

---

src/main/java/com/artipie/debian/metadata/ControlField.java
src/main/java/com/artipie/debian/metadata/UniquePackage.java
src/test/java/com/artipie/debian/metadata/ControlFieldTest.java
src/test/java/com/artipie/debian/metadata/UniquePackageTest.java

Part of #74 
Started to handle duplicates of .deb packages on update: created new `Package` implementation. For now this implementation does not remove duplicate, simply appends new information. Added test and new `ControlFields`, these fields will be used to check duplicates.

Handle .deb duplicates on update

---

src/main/java/com/artipie/debian/metadata/ControlField.java
src/main/java/com/artipie/debian/metadata/UniquePackage.java
src/test/java/com/artipie/debian/metadata/UniquePackageTest.java

Part of #74 
Implemented logic and added tests not to add duplicated info into `Packages` index. 
Will extract duplicated `if-else` statement into separate method is the next PR, also it will be necessary to remove old duplicated `.deb` packages with the help of the list returned by `decompressAppendCompress` method.

Do not add duplicated info into Packages index

---

src/main/java/com/artipie/debian/Debian.java
src/main/java/com/artipie/debian/http/UpdateSlice.java
src/main/java/com/artipie/debian/metadata/UniquePackage.java
src/test/java/com/artipie/debian/metadata/UniquePackageTest.java

Part of #74 
Implemented removing duplicated packages in `UniquePackage`, added more tests and used this implementation istead of `Package.Asto`.

Remove duplicated packages

---

pom.xml
src/main/java/com/artipie/debian/metadata/Release.java
src/main/java/com/artipie/debian/misc/RosUnpackedContent.java
src/test/java/com/artipie/debian/misc/RosUnpackedContentTest.java

Part of #89 
Added `RosUnpackedContent` - this class unpacks `gz` and calculates unpacked content digest and size without loading whole archive into memory and does not copy it to temp file.

Added `RosUnpackedContent` - unpacking with reactive output stream

---

src/test/java/com/artipie/debian/AstoGzArchive.java
src/test/java/com/artipie/debian/DebianTest.java
src/test/java/com/artipie/debian/GzArchive.java
src/test/java/com/artipie/debian/MultiDebianTest.java
src/test/java/com/artipie/debian/http/UpdateSliceTest.java
src/test/java/com/artipie/debian/metadata/PackageAstoTest.java
src/test/java/com/artipie/debian/metadata/ReleaseAstoTest.java
src/test/java/com/artipie/debian/metadata/UniquePackageTest.java

Part of #87 
Extracted test class to work with gz archives without storage: renamed `GzArchive` into `AstoGzArchive` and used `GzArchive` in `MultiDebianTest` and `AstoGzArchive`.

Extracted test class to work with gz

---

src/main/java/com/artipie/debian/MultiPackages.java
src/main/java/com/artipie/debian/metadata/UniquePackage.java
src/test/java/com/artipie/debian/MultiPackagesTest.java
src/test/java/com/artipie/debian/metadata/UniquePackageTest.java

CLoses #96 
While updating or merging `Packages` index extra empty lines should be skipped, corrected code and added corresponding tests.

Skip extra empty lines on Packages update/merge

---

pom.xml
src/main/java/com/artipie/debian/metadata/Package.java

Part of #89 
Updated asto and `StorageValuePipeline` in `Package.Asto` to avoid temp files.

Updated asto, used `StorageValuePipeline` in `Package.Asto`

---

pom.xml
src/main/java/com/artipie/debian/metadata/Package.java
src/main/java/com/artipie/debian/metadata/UniquePackage.java

Part of #89 
Used `StorageValuePipeline` in `UniquePackage` to avoid temp files.

Updated asto, used `StorageValuePipeline` in `UniquePackage`

---

benchmarks/pom.xml
benchmarks/src/main/java/com/artipie/debian/benchmarks/IndexMergeBench.java
benchmarks/src/main/java/com/artipie/debian/benchmarks/RepoUpdateBench.java
pom.xml
src/main/java/com/artipie/debian/http/UpdateSlice.java
src/main/java/com/artipie/debian/metadata/ControlField.java

Updated parent pom, vertx-server, http, asto and cactoos is now used only in test scope.

Update parent pom
